### ISSUE TITLE
android exception

### ISSUE THREAD

**Issue by interfaith** [flutterjanus/flutter_janus_client#138]
I/ViewRootImpl@7ad0280[MainActivity](19190): ViewPostIme pointer 1
I/flutter (19190): [FINE] JanusClient: {janus: attach, transaction: 656006ef-0e0f-41ff-ba9e-fd4b487e436b, session_id: null, plugin: janus.plugin.videoroom}
I/flutter (19190): [INFO] JanusClient: using web socket transport for creating plugin handle
E/flutter (19190): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: No element
E/flutter (19190): #0      Stream.firstWhere.<anonymous closure> (dart:async/stream.dart:1703:9)
E/flutter (19190): #1      _RootZone.runGuarded (dart:async/zone.dart:1582:10)
E/flutter (19190): #2      _DoneStreamSubscription._sendDone (dart:async/stream_impl.dart:699:36)
E/flutter (19190): #3      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (19190): #4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (19190):

This does not happen with browser.

**Comment by shivanshtalwar** [comment]
Which version?

**Comment by interfaith** [comment]
Looks like android studio reveals the trouble

ainActivity]( 7846): ViewPostIme pointer 0
***@***.***[MainActivity]( 7846): ViewPostIme pointer 1
I/flutter ( 7846): [INFO] JanusClient: Creating Session
I/flutter ( 7846): [FINE] JanusClient: fine message
E/flutter ( 7846): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)]
Unhandled Exception: HandshakeException: Handshake error in client (OS
Error:
E/flutter ( 7846): CERTIFICATE_VERIFY_FAILED: unable to get local issuer
certificate(handshake.cc:393))
E/flutter ( 7846): #0      _SecureFilterImpl._handshake
(dart:io-patch/secure_socket_patch.dart:99:46)
E/flutter ( 7846): #1      _SecureFilterImpl.handshake
(dart:io-patch/secure_socket_patch.dart:142:25)
E/flutter ( 7846): #2      _RawSecureSocket._secureHandshake
(dart:io/secure_socket.dart:918:54)
E/flutter ( 7846): #3      _RawSecureSocket._tryFilter
(dart:io/secure_socket.dart:1047:19)
E/flutter ( 7846): <asynchronous suspension>
E/flutter ( 7846):
I/flutter ( 7846): [SEVERE] JanusClient: Connection to given url can't be
established
I/flutter ( 7846):  reason:-WebSocketChannelException: HandshakeException:
Handshake error in client (OS Error:
I/flutter ( 7846): CERTIFICATE_VERIFY_FAILED: unable to get local issuer
certificate(handshake.cc:393))
I/flutter ( 7846): [INFO] JanusClient: Session Created
***@***.***[MainActivity]( 7846): ViewPostIme pointer 0

**Comment by shivanshtalwar** [comment]
Wait what's the whole uri that you are using?

**Comment by interfaith** [comment]
wss://teleden.com
demo https://teleden.com:8080
[image: demoa.png]

**Comment by interfaith** [comment]
the original janus jquery demo
nginx is used so wss -> ws

***@***.***:/opt/janus/etc/janus$ cat janus.transport.websockets.jcfg
# WebSockets stuff: whether they should be enabled, which ports they
# should use, and so on.
general: {
        #events = true                                  # Whether to notify
event handlers about transport events (default=true)
        json = "indented"                               # Whether the JSON
messages should be indented (default),
                                                                        #
plain (no indentation) or compact (no indentation and no spaces)
        #pingpong_trigger = 30                  # After how many seconds of
idle, a PING should be sent
        #pingpong_timeout = 10                  # After how many seconds of
not getting a PONG, a timeout should be detected

        ws = true                                               # Whether
to enable the WebSockets API
        ws_port = 8188                                  # WebSockets server
port
        #ws_interface = "eth0"                  # Whether we should bind
this server to a specific interface only
        ws_ip = "127.0.0.1"                     # Whether we should bind
this server to a specific IP address only
        #ws_unix = "/run/ws.sock"               # Use WebSocket server over
UNIX socket instead of TCP
        wss = false                                             # Whether
to enable secure WebSockets

**Comment by interfaith** [comment]
[image: demos.png]
1. with original demo
2. flutter on browser

**Comment by interfaith** [comment]
it works now via "full chain" cert in nginx conf.
https://stackoverflow.com/questions/54285172/how-to-solve-flutter-certificate-verify-failed-error-while-performing-a-post-req

changed cert.pem to fullchain.pem
***@***.***:/etc/nginx/sites-available$ cat janus
server {
    listen 443 ssl http2;
    server_name teleden.com;

    ssl_certificate /etc/letsencrypt/live/teleden.com/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/teleden.com/privkey.pem;

    location /janus {
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_http_version 1.1;

            proxy_pass http://127.0.0.1:8088;

case closed Thank-you!

**Comment by shivanshtalwar** [comment]
Closing!
