### ISSUE TITLE
Error what try to create an answer

### ISSUE THREAD

**Issue by mazen930** [flutterjanus/flutter_janus_client#154]
When i receive an incoming call and try to call accept
i got error `e = "Unable to RTCPeerConnection::createAnswer: Error (null)"`
This happens whey i try to do as you in example , like the following :
``` 
 var answer = await sip?.createAnswer();
 await sip?.accept(sessionDescription: answer);
  ```
  Any what what could be the problem of how i can solve it ?

**Comment by mazen930** [comment]
I have java script client that works fine with my sip configuration and outbound is working fine with this client , only answering the incoming call is the problem

**Comment by mazen930** [comment]
Any update ?

**Comment by shivanshtalwar** [comment]
Please try using 2.2.14 and tell me if that works for you in the meantime i will fix it

**Comment by shivanshtalwar** [comment]
can you try latest commit if it works for you and let me know?

**Comment by mazen930** [comment]
Actually your commit doesn't fix it , the problem still occurs

**Comment by shivanshtalwar** [comment]
Ok tell me platform on which you are experiencing this issue

**Comment by mazen930** [comment]
> Ok tell me platform on which you are experiencing this issue

IOS

**Comment by mazen930** [comment]
Any update ?

**Comment by shivanshtalwar** [comment]
I still need time to investigate it, thank you for your patience

**Comment by mazen930** [comment]
Any update here ?

**Comment by shivanshtalwar0** [comment]
hi @mazen930 so i tried on two ios simulators with test sip credentials and everything seems to be working just fine i will need more info on your issue to reproduce the problem

**Comment by mazen930** [comment]
Below is the full error appears when i try to create an answer , i use actual phone to test ,not an emulator , i appreciate if you can look it it  
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Unable to RTCPeerConnection::createAnswer: Error (null)
#0      RTCPeerConnectionNative.createAnswer (package:flutter_webrtc/src/native/rtc_peerconnection_impl.dart:355:7)
<asynchronous suspension>
#1      JanusPlugin.createAnswer (package:janus_client/janus_plugin.dart:586:38)
<asynchronous suspension>
#2      Janus.acceptCall (package:maqsam/models/services/web_rtc_clients/janus_client.dart:177:18)
<asynchronous suspension>
```

**Comment by mazen930** [comment]
After debugging , it appears that `await sip?.handleRemoteJsep(event.jsep);` was not configured properly when receiving incoming event , the error was ambiguous and  miss leading me in another direction , i suggest edit your example take that line of of the method that  handles the UI `showIncomingDialogBox` or something like that , anyway thank you @shivanshtalwar0  for your effort and help

**Comment by shivanshtalwar** [comment]
Thanks for your debugging as well, i would appreciate if you could make a little pr for the same if you have time otherwise no problem i will do later

**Comment by mazen930** [comment]
I added a pull request with changes needed to make the sip plugin work correctly , and i will also add another pull request to update the example to be more informative
